// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG_Part2_RaceDay_API.Data;

#nullable disable

namespace PROG_Part2_RaceDay_API.Migrations
{
    [DbContext(typeof(RaceDayDbContext))]
    partial class RaceDayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("EventId");

                    b.HasIndex("RouteId");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_Age", "[MinimumAge] IS NULL OR [MaximumAge] IS NULL OR [MinimumAge] <= [MaximumAge]");

                            t.HasCheckConstraint("CK_Categories_MaximumAge", "[MaximumAge] IS NULL OR [MaximumAge] >= 0");

                            t.HasCheckConstraint("CK_Categories_MinimumAge", "[MinimumAge] IS NULL OR [MinimumAge] >= 0");

                            t.HasCheckConstraint("CK_Categories_Type", "[CategoryType] IN ('Age', 'Distance')");
                        });
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Enrolment", b =>
                {
                    b.Property<int>("EnrolmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrolmentId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.HasKey("EnrolmentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId", "EventId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Enrolments_Participant_Event_Category");

                    b.ToTable("Enrolments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrolments_Status", "[Status] IN ('Confirmed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("OrganiserId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("EventId");

                    b.HasIndex("OrganiserId");

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Events_Distance", "[DistanceKm] > 0");

                            t.HasCheckConstraint("CK_Events_EventType", "[EventType] IN ('Run', 'Walk', 'Cycle')");
                        });
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.RaceRoute", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("AreasCovered")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("FinishLocation")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MapUrl")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("RouteId");

                    b.HasIndex("EventId");

                    b.ToTable("Routes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Routes_Distance", "[DistanceKm] > 0");
                        });
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("EnrolmentId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("FinishTime")
                        .HasColumnType("time");

                    b.Property<int>("FinishingPosition")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("EnrolmentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Results_Enrolment");

                    b.ToTable("Results", null, t =>
                        {
                            t.HasCheckConstraint("CK_Results_Position", "[FinishingPosition] > 0");
                        });
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Organiser', 'Participant')");
                        });
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Category", b =>
                {
                    b.HasOne("PROG_Part2_RaceDay_API.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Categories_Events");

                    b.HasOne("PROG_Part2_RaceDay_API.Models.RaceRoute", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Categories_Routes");
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Enrolment", b =>
                {
                    b.HasOne("PROG_Part2_RaceDay_API.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Enrolments_Categories");

                    b.HasOne("PROG_Part2_RaceDay_API.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Enrolments_Events");

                    b.HasOne("PROG_Part2_RaceDay_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Enrolments_Users");
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Event", b =>
                {
                    b.HasOne("PROG_Part2_RaceDay_API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OrganiserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Events_Users");
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.RaceRoute", b =>
                {
                    b.HasOne("PROG_Part2_RaceDay_API.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Routes_Events");
                });

            modelBuilder.Entity("PROG_Part2_RaceDay_API.Models.Result", b =>
                {
                    b.HasOne("PROG_Part2_RaceDay_API.Models.Enrolment", null)
                        .WithMany()
                        .HasForeignKey("EnrolmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Results_Enrolments");
                });
#pragma warning restore 612, 618
        }
    }
}
